### ISSUE TITLE
Compile from source with ZMQ dependencies

### ISSUE THREAD

**Issue by zpv** [vulpemventures/docker-bitcoin#4]
Hi there! Thank you for your work.

I am running Nigiri on my M1 MacBook Pro and the bitcoin image is crashing due to amd64 emulation issues through qemu.
Specifically, enabling zmq (e.g. `zmqpubrawtx=tcp://0.0.0.0:29000`) results in the container crashing with:

```
2021-10-27T16:57:10Z init message: Loading banlist…
2021-10-27T16:57:10Z SetNetworkActive: true
2021-10-27T16:57:10Z Using /16 prefix for IP bucketing
Operation not permitted (src/thread.cpp:232)
qemu: uncaught target signal 6 (Aborted) - core dumped
```

I'd appreciate multi-arch support https://www.docker.com/blog/multi-arch-build-and-images-the-simple-way/

**Comment by tiero** [comment]
Hey @zpv thanks for opening. I think the problem with ZMQ is more related of [missing libraries in the docker container](https://github.com/bitcoin/bitcoin/blob/master/doc/zmq.md#enabling), since we use the pre-compiled one from bitcoincore.org

Let me test it out and will try to compile from source to enable ZMQ support or arm64 architectures

**Comment by tiero** [comment]
@zpv Renamed the issue to make clear the  task needed for closing this issue and opened new one #5

**Comment by tiero** [comment]
Hopefully if [this action](https://github.com/vulpemventures/docker-bitcoin/runs/4287647645?) works, we will have images for both amd64 and arm64 architectures and the bitcoin core with zmq support

**Comment by tiero** [comment]
Finally I sorted out a stable pipeline to compile Bitcoin for multiple architecture with zmq support.

@zpv  If you using this image with `nigiri` CLI, I also added the support for the zmq in [v0.3.4](https://github.com/vulpemventures/nigiri/releases/tag/v0.3.4), you can update with the installer script (ie. `curl https://getnigiri.vulpem.com | bash`)

Tested on my Apple M1 👌 

```
$ nigiri start
$ nigiri rpc getzmqnotifications
[
  {
    "type": "pubrawblock",
    "address": "tcp://0.0.0.0:28332",
    "hwm": 1000
  },
  {
    "type": "pubrawtx",
    "address": "tcp://0.0.0.0:28333",
    "hwm": 1000
  }
]
```
